### PR TITLE
Fix build & update to cryptsetup 1.6.6

### PR DESCRIPTION
**Pull request by aelmahmoudy**
- Fixed some build issues mentioned in https://github.com/guardianproject/LUKS/issues/5.
  Fixes that I didn't push is a were for util-linux-ng build:
  - I've disabled autogen.sh since it forks bomb with me
  - Patched config.h (during build) to #undef HAVE_MNTENT_H
- cryptsetup 1.6.6: maybe I need to enhance the patch for posix_memalign to instead add a posix_memalign function that is a wrapper around Android's 'memalign'

### CODE REVIEW

**Comment by aelmahmoudy** [comment]
I tested this on OMNI (KitKat 4.4.4), I only tested with a loop-AES volume, didn't try LUKS.
Also, I think that Truecrypt volumes won't work because of the disabled kernel_crypto

**Comment by aelmahmoudy** [comment]
I just tried LUKS but it failed, doesn't that need dmsetup (as in Debian) ?

**Comment by aelmahmoudy** [comment]
In the recent commits, there was no more need to disable autogen.sh for util-linux, details are in this commit: https://github.com/aelmahmoudy/cryptsetup-android/commit/24dc5134169dd51a0b282235b41e857390d5ab7e

But I still do #undef HAVE_MNTENT_H

**Comment by eighthave** [comment]
Sounds like you should take over this project entirely rather than submitting pull requests.  We haven't touched this in years, so you are now a better authority on this.  But I'm happy to answer any questions you have, if I remember enough to say something useful ;-)

**Comment by aelmahmoudy** [comment]
correction: LUKS volumes work fine

**Pull request closed without merging**
